/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignsRouteImport } from './routes/designs'
import { Route as ConceptBotanicalRouteImport } from './routes/concept/botanical'
import { Route as ConceptEarthNoirRouteImport } from './routes/concept/earth-noir'
import { Route as ConceptEditorialRouteImport } from './routes/concept/editorial'
import { Route as ConceptKineticRouteImport } from './routes/concept/kinetic'
import { Route as ConceptNoirRouteImport } from './routes/concept/noir'
import { Route as ConceptNoirBookRouteImport } from './routes/concept.noir-book'
import { Route as ConceptSerifRouteImport } from './routes/concept/serif'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsRoute = DesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptBotanicalRoute = ConceptBotanicalRouteImport.update({
  id: '/concept/botanical',
  path: '/concept/botanical',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptEarthNoirRoute = ConceptEarthNoirRouteImport.update({
  id: '/concept/earth-noir',
  path: '/concept/earth-noir',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptEditorialRoute = ConceptEditorialRouteImport.update({
  id: '/concept/editorial',
  path: '/concept/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptKineticRoute = ConceptKineticRouteImport.update({
  id: '/concept/kinetic',
  path: '/concept/kinetic',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptNoirRoute = ConceptNoirRouteImport.update({
  id: '/concept/noir',
  path: '/concept/noir',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptNoirBookRoute = ConceptNoirBookRouteImport.update({
  id: '/concept/noir-book',
  path: '/concept/noir-book',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptSerifRoute = ConceptSerifRouteImport.update({
  id: '/concept/serif',
  path: '/concept/serif',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/designs': typeof DesignsRoute
  '/concept/botanical': typeof ConceptBotanicalRoute
  '/concept/earth-noir': typeof ConceptEarthNoirRoute
  '/concept/editorial': typeof ConceptEditorialRoute
  '/concept/kinetic': typeof ConceptKineticRoute
  '/concept/noir': typeof ConceptNoirRoute
  '/concept/noir-book': typeof ConceptNoirBookRoute
  '/concept/serif': typeof ConceptSerifRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/designs': typeof DesignsRoute
  '/concept/botanical': typeof ConceptBotanicalRoute
  '/concept/earth-noir': typeof ConceptEarthNoirRoute
  '/concept/editorial': typeof ConceptEditorialRoute
  '/concept/kinetic': typeof ConceptKineticRoute
  '/concept/noir': typeof ConceptNoirRoute
  '/concept/noir-book': typeof ConceptNoirBookRoute
  '/concept/serif': typeof ConceptSerifRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/designs': typeof DesignsRoute
  '/concept/botanical': typeof ConceptBotanicalRoute
  '/concept/earth-noir': typeof ConceptEarthNoirRoute
  '/concept/editorial': typeof ConceptEditorialRoute
  '/concept/kinetic': typeof ConceptKineticRoute
  '/concept/noir': typeof ConceptNoirRoute
  '/concept/noir-book': typeof ConceptNoirBookRoute
  '/concept/serif': typeof ConceptSerifRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/designs'
    | '/concept/botanical'
    | '/concept/earth-noir'
    | '/concept/editorial'
    | '/concept/kinetic'
    | '/concept/noir'
    | '/concept/noir-book'
    | '/concept/serif'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/designs'
    | '/concept/botanical'
    | '/concept/earth-noir'
    | '/concept/editorial'
    | '/concept/kinetic'
    | '/concept/noir'
    | '/concept/noir-book'
    | '/concept/serif'
  id:
    | '__root__'
    | '/'
    | '/designs'
    | '/concept/botanical'
    | '/concept/earth-noir'
    | '/concept/editorial'
    | '/concept/kinetic'
    | '/concept/noir'
    | '/concept/noir-book'
    | '/concept/serif'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignsRoute: typeof DesignsRoute
  ConceptBotanicalRoute: typeof ConceptBotanicalRoute
  ConceptEarthNoirRoute: typeof ConceptEarthNoirRoute
  ConceptEditorialRoute: typeof ConceptEditorialRoute
  ConceptKineticRoute: typeof ConceptKineticRoute
  ConceptNoirRoute: typeof ConceptNoirRoute
  ConceptNoirBookRoute: typeof ConceptNoirBookRoute
  ConceptSerifRoute: typeof ConceptSerifRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs': {
      id: '/designs'
      path: '/designs'
      fullPath: '/designs'
      preLoaderRoute: typeof DesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/botanical': {
      id: '/concept/botanical'
      path: '/concept/botanical'
      fullPath: '/concept/botanical'
      preLoaderRoute: typeof ConceptBotanicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/earth-noir': {
      id: '/concept/earth-noir'
      path: '/concept/earth-noir'
      fullPath: '/concept/earth-noir'
      preLoaderRoute: typeof ConceptEarthNoirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/editorial': {
      id: '/concept/editorial'
      path: '/concept/editorial'
      fullPath: '/concept/editorial'
      preLoaderRoute: typeof ConceptEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/kinetic': {
      id: '/concept/kinetic'
      path: '/concept/kinetic'
      fullPath: '/concept/kinetic'
      preLoaderRoute: typeof ConceptKineticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/noir': {
      id: '/concept/noir'
      path: '/concept/noir'
      fullPath: '/concept/noir'
      preLoaderRoute: typeof ConceptNoirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/noir-book': {
      id: '/concept/noir-book'
      path: '/concept/noir-book'
      fullPath: '/concept/noir-book'
      preLoaderRoute: typeof ConceptNoirBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/serif': {
      id: '/concept/serif'
      path: '/concept/serif'
      fullPath: '/concept/serif'
      preLoaderRoute: typeof ConceptSerifRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignsRoute: DesignsRoute,
  ConceptBotanicalRoute: ConceptBotanicalRoute,
  ConceptEarthNoirRoute: ConceptEarthNoirRoute,
  ConceptEditorialRoute: ConceptEditorialRoute,
  ConceptKineticRoute: ConceptKineticRoute,
  ConceptNoirRoute: ConceptNoirRoute,
  ConceptNoirBookRoute: ConceptNoirBookRoute,
  ConceptSerifRoute: ConceptSerifRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
