/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DesignsRouteImport } from './routes/designs'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ConceptBotanicalRouteImport } from './routes/concept/botanical'
import { Route as ConceptEarthNoirRouteImport } from './routes/concept/earth-noir'
import { Route as ConceptEditorialRouteImport } from './routes/concept/editorial'
import { Route as ConceptKineticRouteImport } from './routes/concept/kinetic'
import { Route as ConceptNoirRouteImport } from './routes/concept/noir'
import { Route as ConceptNoirBookRouteImport } from './routes/concept.noir-book'
import { Route as ConceptNoirTrackRouteImport } from './routes/concept.noir-track'
import { Route as ConceptSerifRouteImport } from './routes/concept/serif'
import { Route as ApiPublicBookingsRouteImport } from './routes/api/public/bookings'
import { Route as ApiPublicBookingsCustomerRouteImport } from './routes/api/public/bookings.customer'
import { Route as ApiPublicBookingsTrackRouteImport } from './routes/api/public/bookings.track'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsRoute = DesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptBotanicalRoute = ConceptBotanicalRouteImport.update({
  id: '/concept/botanical',
  path: '/concept/botanical',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptEarthNoirRoute = ConceptEarthNoirRouteImport.update({
  id: '/concept/earth-noir',
  path: '/concept/earth-noir',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptEditorialRoute = ConceptEditorialRouteImport.update({
  id: '/concept/editorial',
  path: '/concept/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptKineticRoute = ConceptKineticRouteImport.update({
  id: '/concept/kinetic',
  path: '/concept/kinetic',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptNoirRoute = ConceptNoirRouteImport.update({
  id: '/concept/noir',
  path: '/concept/noir',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptNoirBookRoute = ConceptNoirBookRouteImport.update({
  id: '/concept/noir-book',
  path: '/concept/noir-book',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptNoirTrackRoute = ConceptNoirTrackRouteImport.update({
  id: '/concept/noir-track',
  path: '/concept/noir-track',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptSerifRoute = ConceptSerifRouteImport.update({
  id: '/concept/serif',
  path: '/concept/serif',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingsRoute = ApiPublicBookingsRouteImport.update({
  id: '/api/public/bookings',
  path: '/api/public/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingsCustomerRoute =
  ApiPublicBookingsCustomerRouteImport.update({
    id: '/customer',
    path: '/customer',
    getParentRoute: () => ApiPublicBookingsRoute,
  } as any)
const ApiPublicBookingsTrackRoute = ApiPublicBookingsTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => ApiPublicBookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/designs': typeof DesignsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/concept/botanical': typeof ConceptBotanicalRoute
  '/concept/earth-noir': typeof ConceptEarthNoirRoute
  '/concept/editorial': typeof ConceptEditorialRoute
  '/concept/kinetic': typeof ConceptKineticRoute
  '/concept/noir': typeof ConceptNoirRoute
  '/concept/noir-book': typeof ConceptNoirBookRoute
  '/concept/noir-track': typeof ConceptNoirTrackRoute
  '/concept/serif': typeof ConceptSerifRoute
  '/api/public/bookings': typeof ApiPublicBookingsRouteWithChildren
  '/api/public/bookings/customer': typeof ApiPublicBookingsCustomerRoute
  '/api/public/bookings/track': typeof ApiPublicBookingsTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/designs': typeof DesignsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/concept/botanical': typeof ConceptBotanicalRoute
  '/concept/earth-noir': typeof ConceptEarthNoirRoute
  '/concept/editorial': typeof ConceptEditorialRoute
  '/concept/kinetic': typeof ConceptKineticRoute
  '/concept/noir': typeof ConceptNoirRoute
  '/concept/noir-book': typeof ConceptNoirBookRoute
  '/concept/noir-track': typeof ConceptNoirTrackRoute
  '/concept/serif': typeof ConceptSerifRoute
  '/api/public/bookings': typeof ApiPublicBookingsRouteWithChildren
  '/api/public/bookings/customer': typeof ApiPublicBookingsCustomerRoute
  '/api/public/bookings/track': typeof ApiPublicBookingsTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/designs': typeof DesignsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/concept/botanical': typeof ConceptBotanicalRoute
  '/concept/earth-noir': typeof ConceptEarthNoirRoute
  '/concept/editorial': typeof ConceptEditorialRoute
  '/concept/kinetic': typeof ConceptKineticRoute
  '/concept/noir': typeof ConceptNoirRoute
  '/concept/noir-book': typeof ConceptNoirBookRoute
  '/concept/noir-track': typeof ConceptNoirTrackRoute
  '/concept/serif': typeof ConceptSerifRoute
  '/api/public/bookings': typeof ApiPublicBookingsRouteWithChildren
  '/api/public/bookings/customer': typeof ApiPublicBookingsCustomerRoute
  '/api/public/bookings/track': typeof ApiPublicBookingsTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/designs'
    | '/admin'
    | '/admin/login'
    | '/concept/botanical'
    | '/concept/earth-noir'
    | '/concept/editorial'
    | '/concept/kinetic'
    | '/concept/noir'
    | '/concept/noir-book'
    | '/concept/noir-track'
    | '/concept/serif'
    | '/api/public/bookings'
    | '/api/public/bookings/customer'
    | '/api/public/bookings/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/designs'
    | '/admin'
    | '/admin/login'
    | '/concept/botanical'
    | '/concept/earth-noir'
    | '/concept/editorial'
    | '/concept/kinetic'
    | '/concept/noir'
    | '/concept/noir-book'
    | '/concept/noir-track'
    | '/concept/serif'
    | '/api/public/bookings'
    | '/api/public/bookings/customer'
    | '/api/public/bookings/track'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/designs'
    | '/_authenticated/admin'
    | '/admin/login'
    | '/concept/botanical'
    | '/concept/earth-noir'
    | '/concept/editorial'
    | '/concept/kinetic'
    | '/concept/noir'
    | '/concept/noir-book'
    | '/concept/noir-track'
    | '/concept/serif'
    | '/api/public/bookings'
    | '/api/public/bookings/customer'
    | '/api/public/bookings/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DesignsRoute: typeof DesignsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ConceptBotanicalRoute: typeof ConceptBotanicalRoute
  ConceptEarthNoirRoute: typeof ConceptEarthNoirRoute
  ConceptEditorialRoute: typeof ConceptEditorialRoute
  ConceptKineticRoute: typeof ConceptKineticRoute
  ConceptNoirRoute: typeof ConceptNoirRoute
  ConceptNoirBookRoute: typeof ConceptNoirBookRoute
  ConceptNoirTrackRoute: typeof ConceptNoirTrackRoute
  ConceptSerifRoute: typeof ConceptSerifRoute
  ApiPublicBookingsRoute: typeof ApiPublicBookingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs': {
      id: '/designs'
      path: '/designs'
      fullPath: '/designs'
      preLoaderRoute: typeof DesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/botanical': {
      id: '/concept/botanical'
      path: '/concept/botanical'
      fullPath: '/concept/botanical'
      preLoaderRoute: typeof ConceptBotanicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/earth-noir': {
      id: '/concept/earth-noir'
      path: '/concept/earth-noir'
      fullPath: '/concept/earth-noir'
      preLoaderRoute: typeof ConceptEarthNoirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/editorial': {
      id: '/concept/editorial'
      path: '/concept/editorial'
      fullPath: '/concept/editorial'
      preLoaderRoute: typeof ConceptEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/kinetic': {
      id: '/concept/kinetic'
      path: '/concept/kinetic'
      fullPath: '/concept/kinetic'
      preLoaderRoute: typeof ConceptKineticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/noir': {
      id: '/concept/noir'
      path: '/concept/noir'
      fullPath: '/concept/noir'
      preLoaderRoute: typeof ConceptNoirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/noir-book': {
      id: '/concept/noir-book'
      path: '/concept/noir-book'
      fullPath: '/concept/noir-book'
      preLoaderRoute: typeof ConceptNoirBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/noir-track': {
      id: '/concept/noir-track'
      path: '/concept/noir-track'
      fullPath: '/concept/noir-track'
      preLoaderRoute: typeof ConceptNoirTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/serif': {
      id: '/concept/serif'
      path: '/concept/serif'
      fullPath: '/concept/serif'
      preLoaderRoute: typeof ConceptSerifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bookings': {
      id: '/api/public/bookings'
      path: '/api/public/bookings'
      fullPath: '/api/public/bookings'
      preLoaderRoute: typeof ApiPublicBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bookings/customer': {
      id: '/api/public/bookings/customer'
      path: '/customer'
      fullPath: '/api/public/bookings/customer'
      preLoaderRoute: typeof ApiPublicBookingsCustomerRouteImport
      parentRoute: typeof ApiPublicBookingsRoute
    }
    '/api/public/bookings/track': {
      id: '/api/public/bookings/track'
      path: '/track'
      fullPath: '/api/public/bookings/track'
      preLoaderRoute: typeof ApiPublicBookingsTrackRouteImport
      parentRoute: typeof ApiPublicBookingsRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicBookingsRouteChildren {
  ApiPublicBookingsCustomerRoute: typeof ApiPublicBookingsCustomerRoute
  ApiPublicBookingsTrackRoute: typeof ApiPublicBookingsTrackRoute
}

const ApiPublicBookingsRouteChildren: ApiPublicBookingsRouteChildren = {
  ApiPublicBookingsCustomerRoute: ApiPublicBookingsCustomerRoute,
  ApiPublicBookingsTrackRoute: ApiPublicBookingsTrackRoute,
}

const ApiPublicBookingsRouteWithChildren =
  ApiPublicBookingsRoute._addFileChildren(ApiPublicBookingsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DesignsRoute: DesignsRoute,
  AdminLoginRoute: AdminLoginRoute,
  ConceptBotanicalRoute: ConceptBotanicalRoute,
  ConceptEarthNoirRoute: ConceptEarthNoirRoute,
  ConceptEditorialRoute: ConceptEditorialRoute,
  ConceptKineticRoute: ConceptKineticRoute,
  ConceptNoirRoute: ConceptNoirRoute,
  ConceptNoirBookRoute: ConceptNoirBookRoute,
  ConceptNoirTrackRoute: ConceptNoirTrackRoute,
  ConceptSerifRoute: ConceptSerifRoute,
  ApiPublicBookingsRoute: ApiPublicBookingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
